version: '3.0'

services:

    hlz-go:
        image: golang:1.15
        container_name: puppeteer-go-app
        working_dir: /app
        restart: always
        volumes:
            - ./:/app:cached
            - /tmp/comic_api:/tmp/comic_api:cached
        ports:
            - 8100:8100
        environment:
            TZ: Asia/Shanghai
            NODE_ENV: production
        networks:
            default:
                ipv4_address: 172.38.0.2
        command:  bash -c "export GO111MODULE=on && export GOPROXY=https://goproxy.io && export TERM=xterm && mkdir -p /tmp/comic_api && cd /app && make cr"
        # cgroups 部署资源限制
        deploy:
            resources:
                limits: # cpu最大使用数
                    cpus: '0.3' # 该服务cpu资源可用百分比，单个cpu打满就是 100%, 这里的 1.0 就是 100% 的 意思
                    memory: 200M
                    #reservations: # cpu最小使用数 --- 只能在 swarm 中用
                    #cpus: '0.2'
                    #memory: 200M

networks:
    default:
        external:
            name: network_puppeteer_go

