package owngin

const (
	/**
	 * 业务响应码
	 */
	HTTP_RESPONSE_CODE_SUCCESS          = 200
	HTTP_RESPONSE_CODE_PARAM_INVALID    = 400
	HTTP_RESPONSE_CODE_SOURCE_NOT_FOUND = 404
	HTTP_RESPONSE_CODE_UNKNOWN_FAIL     = 500
	HTTP_RESPONSE_CODE_GENERAL_FAIL     = 501
	HTTP_RESPONSE_CODE_TIMEOUT          = 502
	HTTP_RESPONSE_CODE_GATEWAY_TIMEOUT  = 504
)
