// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel(in *jlexer.Lexer, out *ChapterListResponseItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "sequence":
			out.Sequence = int(in.Int())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel(out *jwriter.Writer, in ChapterListResponseItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"sequence\":"
		out.RawString(prefix)
		out.Int(int(in.Sequence))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChapterListResponseItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChapterListResponseItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChapterListResponseItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChapterListResponseItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel(l, v)
}
func easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel1(in *jlexer.Lexer, out *ChapterListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "list":
			if in.IsNull() {
				in.Skip()
				out.List = nil
			} else {
				in.Delim('[')
				if out.List == nil {
					if !in.IsDelim(']') {
						out.List = make([]*ChapterListResponseItem, 0, 8)
					} else {
						out.List = []*ChapterListResponseItem{}
					}
				} else {
					out.List = (out.List)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *ChapterListResponseItem
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(ChapterListResponseItem)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.List = append(out.List, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel1(out *jwriter.Writer, in ChapterListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"list\":"
		out.RawString(prefix[1:])
		if in.List == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.List {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChapterListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChapterListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChapterListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChapterListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel1(l, v)
}
func easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel2(in *jlexer.Lexer, out *ChapterListParam) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ComicId":
			out.ComicId = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel2(out *jwriter.Writer, in ChapterListParam) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ComicId\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ComicId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChapterListParam) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChapterListParam) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE762f52EncodeNodePuppeteerExampleGoApiModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChapterListParam) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChapterListParam) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE762f52DecodeNodePuppeteerExampleGoApiModel2(l, v)
}
