// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7950832dDecodeNodePuppeteerExampleGoApiModel(in *jlexer.Lexer, out *ComicListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "list":
			if in.IsNull() {
				in.Skip()
				out.List = nil
			} else {
				in.Delim('[')
				if out.List == nil {
					if !in.IsDelim(']') {
						out.List = make([]*Comic, 0, 8)
					} else {
						out.List = []*Comic{}
					}
				} else {
					out.List = (out.List)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *Comic
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Comic)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.List = append(out.List, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7950832dEncodeNodePuppeteerExampleGoApiModel(out *jwriter.Writer, in ComicListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"list\":"
		out.RawString(prefix[1:])
		if in.List == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.List {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ComicListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7950832dEncodeNodePuppeteerExampleGoApiModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ComicListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7950832dEncodeNodePuppeteerExampleGoApiModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ComicListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7950832dDecodeNodePuppeteerExampleGoApiModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ComicListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7950832dDecodeNodePuppeteerExampleGoApiModel(l, v)
}
func easyjson7950832dDecodeNodePuppeteerExampleGoApiModel1(in *jlexer.Lexer, out *ComicListParam) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Page":
			out.Page = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7950832dEncodeNodePuppeteerExampleGoApiModel1(out *jwriter.Writer, in ComicListParam) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Page\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Page))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ComicListParam) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7950832dEncodeNodePuppeteerExampleGoApiModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ComicListParam) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7950832dEncodeNodePuppeteerExampleGoApiModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ComicListParam) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7950832dDecodeNodePuppeteerExampleGoApiModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ComicListParam) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7950832dDecodeNodePuppeteerExampleGoApiModel1(l, v)
}
func easyjson7950832dDecodeNodePuppeteerExampleGoApiModel2(in *jlexer.Lexer, out *Comic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.Model = new(Model)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "channel":
			out.Channel = int(in.Int())
		case "source_id":
			out.SourceID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "pic":
			out.Pic = string(in.String())
		case "intro":
			out.Intro = string(in.String())
		case "max_sequence":
			out.MaxSequence = int(in.Int())
		case "weight":
			out.Weight = int(in.Int())
		case "tag":
			out.Tag = int(in.Int())
		case "id":
			out.ID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7950832dEncodeNodePuppeteerExampleGoApiModel2(out *jwriter.Writer, in Comic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"channel\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Channel))
	}
	{
		const prefix string = ",\"source_id\":"
		out.RawString(prefix)
		out.Int(int(in.SourceID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"pic\":"
		out.RawString(prefix)
		out.String(string(in.Pic))
	}
	{
		const prefix string = ",\"intro\":"
		out.RawString(prefix)
		out.String(string(in.Intro))
	}
	{
		const prefix string = ",\"max_sequence\":"
		out.RawString(prefix)
		out.Int(int(in.MaxSequence))
	}
	{
		const prefix string = ",\"weight\":"
		out.RawString(prefix)
		out.Int(int(in.Weight))
	}
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix)
		out.Int(int(in.Tag))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Comic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7950832dEncodeNodePuppeteerExampleGoApiModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Comic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7950832dEncodeNodePuppeteerExampleGoApiModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Comic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7950832dDecodeNodePuppeteerExampleGoApiModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Comic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7950832dDecodeNodePuppeteerExampleGoApiModel2(l, v)
}
