// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package vo

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	po "node_puppeteer_example_go/common/model/po"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson65b40f0eDecodeNodePuppeteerExampleGoCommonModelVo(in *jlexer.Lexer, out *PageListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "list":
			if in.IsNull() {
				in.Skip()
				out.List = nil
			} else {
				in.Delim('[')
				if out.List == nil {
					if !in.IsDelim(']') {
						out.List = make([]*po.ComicPage, 0, 8)
					} else {
						out.List = []*po.ComicPage{}
					}
				} else {
					out.List = (out.List)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *po.ComicPage
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(po.ComicPage)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.List = append(out.List, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson65b40f0eEncodeNodePuppeteerExampleGoCommonModelVo(out *jwriter.Writer, in PageListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"list\":"
		out.RawString(prefix[1:])
		if in.List == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.List {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PageListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson65b40f0eEncodeNodePuppeteerExampleGoCommonModelVo(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PageListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson65b40f0eEncodeNodePuppeteerExampleGoCommonModelVo(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PageListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson65b40f0eDecodeNodePuppeteerExampleGoCommonModelVo(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PageListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson65b40f0eDecodeNodePuppeteerExampleGoCommonModelVo(l, v)
}
func easyjson65b40f0eDecodeNodePuppeteerExampleGoCommonModelVo1(in *jlexer.Lexer, out *PageListParam) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Channel":
			out.Channel = int(in.Int())
		case "SourceId":
			out.SourceId = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson65b40f0eEncodeNodePuppeteerExampleGoCommonModelVo1(out *jwriter.Writer, in PageListParam) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Channel\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Channel))
	}
	{
		const prefix string = ",\"SourceId\":"
		out.RawString(prefix)
		out.Int(int(in.SourceId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PageListParam) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson65b40f0eEncodeNodePuppeteerExampleGoCommonModelVo1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PageListParam) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson65b40f0eEncodeNodePuppeteerExampleGoCommonModelVo1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PageListParam) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson65b40f0eDecodeNodePuppeteerExampleGoCommonModelVo1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PageListParam) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson65b40f0eDecodeNodePuppeteerExampleGoCommonModelVo1(l, v)
}
